Repository jupyterhub/autodoc-traits, pull requests merged in 2022-12, with the labels that each got.

#10 Fix failure to use autoclass on non-traitlets configurable classes
  autodoc_traits/autodoc_traits.py
Labels: bug

#15 pre-commit: add typical jupyterhub org config
  .flake8
  .pre-commit-config.yaml
  autodoc_traits/autodoc_traits.py
  pyproject.toml
  setup.py
Labels: maintenance

#14 Refresh README, RELEASE, and CHANGELOG
  CHANGELOG.md
  README.md
  RELEASE.md
Labels: documentation

#18 Automatically register the sphinx.ext.autodoc extension
  README.md
  autodoc_traits/autodoc_traits.py
Labels: enhancement

#16 docs: add fixme note about unexpected inherited-members option
  autodoc_traits/autodoc_traits.py
Labels: documentation

#20 ci: add dependabot.yaml and update release workflow
  .github/dependabot.yaml
  .github/workflows/publish.yml
  .github/workflows/release.yaml
  RELEASE.md
Labels: ci

#32 avoid putting `c.Class.trait` annotation on non-config traits
  autodoc_traits.py
  tests/test_autodoc_traits.py
Labels: bug

#33 register traits with a help string as documented for `autoclass`
  autodoc_traits.py
  tests/docs/source/autotrait/nohelp.rst
  tests/test_autodoc_traits.py
Labels: bug
